"""added new columns in orders table, changed the properties of some columns

Revision ID: 2888b8fc9b75
Revises: 29b40dced8b5
Create Date: 2025-05-27 21:39:05.503045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2888b8fc9b75'
down_revision: Union[str, None] = '29b40dced8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('issue_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('issue_place', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('issue_datetime', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('order_text', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_price', sa.Numeric(precision=7, scale=2), server_default=sa.text('0.00'), nullable=False))
    op.add_column('orders', sa.Column('order_issued', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.add_column('orders', sa.Column('order_source', sa.String(), nullable=True))
    op.alter_column('orders', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'client_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'order_source')
    op.drop_column('orders', 'order_issued')
    op.drop_column('orders', 'delivery_price')
    op.drop_column('orders', 'order_text')
    op.drop_column('orders', 'issue_datetime')
    op.drop_column('orders', 'issue_place')
    op.drop_column('orders', 'issue_method')
    op.drop_column('orders', 'client_phone')
    # ### end Alembic commands ###
