"""set cascade deletion for orders and items depending on session

Revision ID: 29b40dced8b5
Revises: bb6652528df9
Create Date: 2025-05-23 20:19:06.788295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b40dced8b5'
down_revision: Union[str, None] = 'bb6652528df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_order_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint('orders_session_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_session_id_fkey', 'orders', 'sessions', ['session_id'], ['session_id'])
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_order_id_fkey', 'items', 'orders', ['order_id'], ['order_id'])
    # ### end Alembic commands ###
