"""empty message

Revision ID: 59eef8431860
Revises: 6deeea358b49
Create Date: 2025-05-31 13:42:48.709180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59eef8431860'
down_revision: Union[str, None] = '6deeea358b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_price',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_price',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###
