"""empty message

Revision ID: 5eeacbef04c9
Revises: 45d261218e19
Create Date: 2025-06-23 18:41:00.032536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eeacbef04c9'
down_revision: Union[str, None] = '45d261218e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        'transactions', 'transaction_datetime',
        type_=sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        existing_nullable=False
    )
    
    op.alter_column(
        'orders', 'creation_datetime',
        type_=sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        existing_nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
