"""created a row to specify the date when an order was created

Revision ID: 6deeea358b49
Revises: 2888b8fc9b75
Create Date: 2025-05-29 20:11:24.812151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = '6deeea358b49'
down_revision: Union[str, None] = '2888b8fc9b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('creation_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    now = datetime.now(timezone.utc).isoformat()
    op.execute(f"UPDATE orders SET creation_datetime = '{now}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'creation_datetime')
    # ### end Alembic commands ###
