"""empty message

Revision ID: a0c4035483e9
Revises: 5eeacbef04c9
Create Date: 2025-07-02 18:38:44.431661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c4035483e9'
down_revision: Union[str, None] = '5eeacbef04c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_info', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_note')
    op.drop_column('transactions', 'transaction_info')
    # ### end Alembic commands ###
