"""added the two new columns to transactions to store note in the future and save parts

Revision ID: a226d5718d74
Revises: 5eeacbef04c9
Create Date: 2025-07-03 20:23:16.673668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a226d5718d74'
down_revision: Union[str, None] = '5eeacbef04c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_info', postgresql.ARRAY(sa.Numeric(precision=9, scale=3)), nullable=True))
    op.add_column('transactions', sa.Column('transaction_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_note')
    op.drop_column('transactions', 'transaction_info')
    # ### end Alembic commands ###
