"""changed the session columns

Revision ID: bb6652528df9
Revises: 
Create Date: 2025-05-21 12:21:05.647067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6652528df9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_name', sa.String(), nullable=False, server_default=sa.text("'temp'")))
    op.add_column('sessions', sa.Column('session_descr', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('session_arch', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.execute(
        """
        UPDATE sessions
        SET session_name = TO_CHAR(session_date, 'DD-MM-YYYY') || ' ' || session_place
        """
    )
    op.alter_column('sessions', 'session_name', server_default=None)
    op.execute(
        """
        UPDATE sessions
        SET session_descr = TO_CHAR(session_date, 'DD-MM-YYYY') || ' ' || session_place || ' ' || session_method
        """
    )
    op.drop_column('sessions', 'session_place')
    op.drop_column('sessions', 'session_date')
    op.drop_column('sessions', 'session_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('sessions', sa.Column('session_method', sa.VARCHAR(length=20), nullable=False, server_default=sa.text("'temp'")))
    op.add_column('sessions', sa.Column('session_date', sa.TIMESTAMP(), nullable=False, server_default=sa.text("'1970-01-01 00:00:00'")))
    op.add_column('sessions', sa.Column('session_place', sa.VARCHAR(), nullable=False, server_default=sa.text("'temp'")))

    op.execute("""
        UPDATE sessions
        SET session_place = SUBSTRING(session_name FROM POSITION(' ' IN session_name) + 1)
    """)
    op.alter_column('sessions', 'session_place', server_default=None)

    op.execute("""
        UPDATE sessions
        SET session_method = SUBSTRING(session_descr FROM
            (POSITION(' ' IN session_descr) + 1 + POSITION(' ' IN SUBSTRING(session_descr FROM POSITION(' ' IN session_descr) + 1)))
        )
    """)
    op.alter_column('sessions', 'session_method', server_default=None)

    op.execute("""
        UPDATE sessions
        SET session_date = TO_TIMESTAMP(SUBSTRING(session_name FROM 1 FOR 10), 'DD-MM-YYYY')
        WHERE LENGTH(session_name) >= 10
            AND SUBSTRING(session_name FROM 3 FOR 1) = '-'
            AND SUBSTRING(session_name FROM 6 FOR 1) = '-'
    """)
    op.alter_column('sessions', 'session_date', server_default=None)

    op.drop_column('sessions', 'session_arch')
    op.drop_column('sessions', 'session_descr')
    op.drop_column('sessions', 'session_name')